"""Initial migration

Revision ID: 028ebc91f9de
Revises: 
Create Date: 2025-03-21 13:35:25.403709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '028ebc91f9de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('check_in',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('check_out',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability', sa.Boolean(), nullable=True))
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('availability')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('check_out',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('check_in',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)

    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=False),
    sa.Column('password', sa.TEXT(), nullable=False),
    sa.Column('role', sa.TEXT(), nullable=False),
    sa.CheckConstraint("role IN('customer', 'admin')"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###
